### ISSUE TITLE
Investigate bundling distil-medium.en

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-whisper#12]
https://huggingface.co/distil-whisper/distil-medium.en

https://huggingface.co/yumfood/whisper_distil_medium_en_ct2/tree/main

**Comment by fire** [comment]
```
git clone https://huggingface.co/yumfood/whisper_distil_medium_en_ct2
git clone https://github.com/V-Sekai/v-sekai.whisper.git
```

**Comment by fire** [comment]
./quantize ggml-large-32-2.en.bin ggml-large-5_0.enq.bin q5_0

**Comment by fire** [comment]
Rename `ggml-large-5_1.en.bin` to `ggml-tiny.en.bin`. Probably needs to be a string path.

**Comment by fire** [comment]
!!!

Move the file to ```res://addons/godot_whisper/models/ggml-tiny.en.bin```

**Comment by fire** [comment]
ggml-distilled-large-q5_1.en is too slow

**Comment by fire** [comment]
`./quantize ggml-medium-32-2.en.bin ggml-tiny.en.bin q5_1`

```
ggml_common_quantize_0: model size  =  1504.42 MB
ggml_common_quantize_0: quant size  =   293.35 MB | ftype = 9 (q5_1)
ggml_common_quantize_0: hist: 0.073 0.058 0.059 0.061 0.064 0.066 0.069 0.081 0.072 0.061 0.059 0.056 0.054 0.052 0.052 0.065

main: quantize time =  2933.80 ms
main:    total time =  2933.80 ms
```

**Comment by fire** [comment]
See also https://github.com/Vaibhavs10/insanely-fast-whisper

**Comment by fire** [comment]
https://huggingface.co/distil-whisper/distil-small.en small size!

**Comment by Ughuuu** [comment]
I added it to the option dropdown for small size. It can also be downloaded manually if people want. It's just not that fast imo.

**Comment by fire** [comment]
Thanks
