### ISSUE TITLE
Re-fix Mac signing

### ISSUE THREAD

**Issue by Ughuuu** [V-Sekai/godot-whisper#19]
Right now it gives code signing invalid error when opening lib

**Comment by fire** [comment]
Is this done?

**Comment by Ughuuu** [comment]
Nope, haven't gotten to it. I was looking into iOS signing and got stuck on that.

**Comment by Ughuuu** [comment]
Problem is this:
```
Granting access to keychain...
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
```

So I need to double check secrets, or where I send them, maybe I dont use double quotes or a space or something went in.

**Comment by Ughuuu** [comment]
All problems I had, now docuemnted nicely in the godot-cpp-template for I use here. So in that readme people can check how to generate secrets, and they should work for most cases.

**Comment by Ughuuu** [comment]
Fixed it seems like. For future me to understand. The problem was that the framework folder had the .metal file, and signing process didnt like that. It succeded, no major error just didnt work.
I removed the metal file, and it seems to load, though it throws 2 errors(Seems like it uses metal, I cant be 100% sure though. On both mac and iphone works really fast).
