### ISSUE TITLE
Switching to physics process improves performance?!

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-whisper#23]
Really odd

**Comment by Ughuuu** [comment]
Tested on Mac, there isn't an improvement. But I can leave it to physics perform if it runs faster on windows.

**Comment by fire** [comment]
I close this because I forgot the exact context.

**Comment by Ughuuu** [comment]
The context was that if you used in godot physics_process instead of process to call the function that processes the text you got faster/better results(in windows). On Mac I wasn't able to replicate it.
