### ISSUE TITLE
32 bit android and web builds fail with CBLast or OpenCL not supporting 32 bit

### ISSUE THREAD

**Issue by Ughuuu** [V-Sekai/godot-whisper#25]
Reenable them somehow.

**Comment by fire** [comment]
I don't think we're crashing anymore.

**Comment by Ughuuu** [comment]
We aren't supporting webgl builds still. Not sure about 32 bit android also.

**Comment by Ughuuu** [comment]
This isn't about crash, it's about web support for whisper.

**Comment by Ughuuu** [comment]
Seems like builds fail simply because of conversion issue(from long to uint or smht like that). For now building with:
env.Append(CCFLAGS=["-Wno-c++11-narrowing"])
To see if it fixes.
I am not 100% sure if it will run correctly with optimization on web, but at least for now to see if it builds.
