### ISSUE TITLE
Can't run iOS build, crashes code in whisper metal init.

### ISSUE THREAD

**Issue by Ughuuu** [V-Sekai/godot-whisper#28]

**Comment by fire** [comment]
Is this still happening?

**Comment by Ughuuu** [comment]
Now it crashes differently, I am not able to make godot work at all with mic. And then if I remove mic recording, it still crashes somewhere(in simulator) and on phone it just freezes my phone completely.

**Comment by fire** [comment]
Is this still crashing?

**Comment by Ughuuu** [comment]
Wouldn't know, I have upgraded whisper, maybe now it works. I'll test it tomorrow.

**Comment by Ughuuu** [comment]
Works now!
