### ISSUE TITLE
Publish to Godot Asset Library

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-whisper#47]
What are the steps needed?

**Comment by Ughuuu** [comment]
Basically create an asset there and put as files this repo release(that we will make).
Ideally I want all major platforms tested, after mac signing and testing ios we should be good to PUBLISH!!!!

**Comment by Ughuuu** [comment]
I say we finally publish to asset store as is, it's not great but then again, when will it ever be.

**Comment by fire** [comment]
![image](https://github.com/V-Sekai/godot-whisper/assets/32321/97d45aa0-823b-429d-ac67-edd0bb087df9)

**Comment by fire** [comment]
- Asset Name: `Godot Whisper Addon`
- Description: `An addon for the Godot Engine that enables realtime audio transcription, supports Metal for Apple devices, and runs on a separate thread. Open-source under the MIT license for broad community usage.`
- Category: Tools
- License: `MIT`
- Repository host: `GitHub`
- Repository URL: `https://github.com/V-Sekai/godot-whisper`
- Issue URL: https://github.com/V-Sekai/godot-whisper/issues
- Godot version: (Specify the version of Godot Engine this addon is compatible with, which you can find in the repository documentation or by testing the addon yourself)
- Asset Version*: `0.0.2` (Based on the latest release information from the repository)
- Download Commit/SHA*: a2908b5add22fb91c7703b4c521e119f49c7910b

Here's a rough draft of the fields.

**Comment by fire** [comment]
Do we have a logo?

**Comment by Ughuuu** [comment]
No logo. I was thinking of reusing whisper or whisper cpp logo

**Comment by fire** [comment]
I think if we can't think of something godot-whisper might be ok as a wordmark. I remember many Discords servers renaming and changing their logos because they reused a project's identity.

**Comment by fire** [comment]
![image](https://github.com/V-Sekai/godot-whisper/assets/32321/5a3486d7-2502-404b-81a4-a836eeaf8e14)

Sent for review..

**Comment by fire** [comment]
![image](https://github.com/V-Sekai/godot-whisper/assets/32321/55c7a322-0217-41a6-9a65-4d34aa9fac99)

**Comment by fire** [comment]
![image](https://github.com/V-Sekai/godot-whisper/assets/32321/2d51da41-48cd-4222-b281-520a3d01c289)

**Comment by fire** [comment]
![image](https://github.com/V-Sekai/godot-whisper/assets/32321/0f396dbc-90b3-42a3-ae27-74d79ff51567)
