### ISSUE TITLE
Does not work on Export

### ISSUE THREAD

**Issue by Blackout4344** [V-Sekai/godot-whisper#62]
The speech to text works fine in the editor, but on export, it doesn't work and gives me these errors. 

Godot version: 4.2.1
OS: MacOS Sonoma 14.2.1, M1

<img width="588" alt="Screenshot 2024-03-14 at 3 29 55 PM" src="https://github.com/V-Sekai/godot-whisper/assets/108584340/7f94c7e7-9bb2-4b86-aa98-7873a23dbe1a">

**Comment by Ughuuu** [comment]
On export to what platform? On export to macos? or iOS? are there any there errors?

**Comment by Ughuuu** [comment]
If it's export to iOS it's related to this, I'm working on it:
https://github.com/V-Sekai/godot-whisper/issues/60

**Comment by Blackout4344** [comment]
> On export to what platform? On export to macos? or iOS? are there any there errors?

For MacOS, and the only errors are
```
SCRIPT ERROR: Parse Error: Could not resolve class "StreamToText".
          at: GDScript::reload (res://addons/godot_whisper/capture_stream_to_text.gd:0)
ERROR: Failed to load script "res://addons/godot_whisper/capture_stream_to_text.gd" with error "Parse error".
   at: load (modules/gdscript/gdscript.cpp:2788)
ERROR: whisper_backend_init: ggml_backend_metal_init() failed
```

**Comment by Ughuuu** [comment]
Is it debug or release export for macOS?

**Comment by Blackout4344** [comment]
> Is it debug or release export for macOS?
> 
> Edit: Reproduced it locally with debug build.

I'm not exactly sure what you mean, but I think it's debug

**Comment by Ughuuu** [comment]
I created bug on godot-cpp side, seems to come from there:
https://github.com/godotengine/godot-cpp/issues/1414
For now as workaround I will hide the problem in godot-whisper by not extending a class more than once from GDExtension.
