### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by marischou** [V-Sekai/godot-whisper#64]
Hello, I'm having issues trying to get the extension to work.

#### Godot version:
Godot_v4.1.4-rc1_linux.x86_64 

#### Steps to reproduce:
1. Download Godot Whisper from AssetLib
2. Error

I tried downloading latest 1.0.4 version from Github, extracted addon folder to project, still same error.
Restarting produces the same error.

#### Error message:
```Error loading extension: res://addons/godot_whisper/godot_whisper.gdextension```

#### Terminal error log:
```
...
     at: _editor_init (modules/gltf/register_types.cpp:73)

ERROR: Can't open dynamic library: /Data/PROGRAMMING/godot/try_whisper/addons/godot_whisper/bin/libgodot_whisper.linux.template_release.x86_64.so. Error: /Data/PROGRAMMING/godot/try_whisper/addons/godot_whisper/bin/libgodot_whisper.linux.template_release.x86_64.so: undefined symbol: clBuildProgram.
   at: open_dynamic_library (drivers/unix/os_unix.cpp:650)

ERROR: GDExtension dynamic library not found: /Data/PROGRAMMING/godot/try_whisper/addons/godot_whisper/bin/libgodot_whisper.linux.template_release.x86_64.so
   at: open_library (core/extension/gdextension.cpp:455)

ERROR: Failed loading resource: res://addons/godot_whisper/godot_whisper.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:273)
...
```

**Comment by Ughuuu** [comment]
Hi. Thanks for reporting. So far only tested build on windows and mac. Linux isnt that well tested, just that build passes.
@fire you wanna take a look or should i try?
