### ISSUE TITLE
Multiple quick clicks on the "running button" will inevitably trigger a crash

### ISSUE THREAD

**Issue by aiaimimi0920** [V-Sekai/godot-whisper#69]
https://github.com/V-Sekai/godot-whisper/assets/153103332/c5abe9e6-8fc5-4ab6-8ae2-4001ab97ed1f

It should be related to the call to Thread

**Comment by Ughuuu** [comment]
Will check. Now that we are using thread in gdscript should be easier to change/investigate/fix.

**Comment by fire** [comment]
We need to update the addon on the asset library right?

**Comment by Ughuuu** [comment]
In a bit, i will tell you after i make a release. Went away from pc after the pr and build failed, need to rerun it. On windows it falls intermittently at upload stage.
