### ISSUE TITLE
.wav file issues

### ISSUE THREAD

**Issue by JBlank19** [V-Sekai/godot-whisper#74]
Good day!

The audio transcription node does not work with most of the .wav files. For example the .wav files produced from godot itself when recording the mic. However, it does work with the capture node. It seems some issue with the formatting of the input data.

**Comment by fire** [comment]
As far as I know we wrote the capture node because we weren't able to get the record node to work 3-4 years ago.

**Comment by AllenDang** [comment]
@fire My god, I just wasted like half a day trying to figure out why the recorded wav doesn't work...

**Comment by fire** [comment]
@AllenDang Here was the original design documentation. https://github.com/godotengine/godot-proposals/issues/2013

**Comment by Ughuuu** [comment]
The .wav will not work since the API receives the direct sound buffer data after/if you would decode the .wav:
`Array transcribe(PackedFloat32Array buffer, String initial_prompt, int audio_ctx); `


If you just read the .wav file, I think that would have some extra encoding data.

**Comment by Ughuuu** [comment]
Will update readme to say that .wav doesn't work and that transcribe currently only works with a float32 buffer. For wav you have to decode it yourself.
