### ISSUE TITLE
Could not find base class "SpeechToText"

### ISSUE THREAD

**Issue by snorreks** [V-Sekai/godot-whisper#76]
The SpeechToText class is not found in gd script or when trying to create a new node.

Plugin  version: 1.1.0 (release tag from download says 1.0.5, but plugin.cfg says 1.1.0)
Godot Engine v4.2.2
OS: Linux (NixOS)

Steps to reproduce:
1. Downloaded from https://github.com/V-Sekai/godot-whisper/releases/tag/v1.0.5
2. Copied addons folder to my project
3. Added the plugin in the editor. I could download models through the interface, but SpeechToText is not working

I also tried to update the imports in godot_whisper.gdextension and include it in project.godot but that did not work either.

<details>
  <summary>project.godot</summary>
    <pre><code>
config_version=5

[application]

config/features=PackedStringArray("4.2", "GL Compatibility")

[editor_plugins]

enabled=PackedStringArray("res://addons/godot_whisper/plugin.cfg")

[native_extensions]

paths=PackedStringArray("res://addons/godot_whisper/godot_whisper.gdextension")

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
textures/vram_compression/import_etc2_astc=true

...
  </code></pre>
</details>

<details>
  <summary>addons/godot_whisper/godot_whisper.gdextension</summary>
    <pre><code>
[configuration]

entry_symbol = "godot_whisper_library_init"
compatibility_minimum = 4.1

[libraries]

macos.debug = "res://addons/godot_whisper/bin/libgodot_whisper.macos.template_release.universal.framework"
macos.release = "res://addons/godot_whisper/bin/libgodot_whisper.macos.template_release.universal.framework"
macos.debug.double = "res://addons/godot_whisper/bin/libgodot_whisper.macos.template_release.double.universal.framework"
macos.release.double = "res://addons/godot_whisper/bin/libgodot_whisper.macos.template_release.double.universal.framework"

ios.debug = "res://addons/godot_whisper/bin/libgodot_whisper.ios.template_release.arm64.dylib"
ios.release = "res://addons/godot_whisper/bin/libgodot_whisper.ios.template_release.arm64.dylib"
ios.debug.double = "res://addons/godot_whisper/bin/libgodot_whisper.ios.template_release.double.arm64.dylib"
ios.release.double = "res://addons/godot_whisper/bin/libgodot_whisper.ios.template_release.double.arm64.dylib"

windows.debug.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.x86_32.dll"
windows.release.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.x86_32.dll"
windows.debug.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.x86_64.dll"
windows.release.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.x86_64.dll"
windows.debug.double.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.double.x86_32.dll"
windows.release.double.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.double.x86_32.dll"
windows.debug.double.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.double.x86_64.dll"
windows.release.double.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.windows.template_release.double.x86_64.dll"

linux.debug.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.linux.template_release.x86_64.so"
linux.release.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.linux.template_release.x86_64.so"
linux.debug.double.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.linux.template_release.double.x86_64.so"
linux.release.double.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.linux.template_release.double.x86_64.so"

android.debug.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.x86_64.so"
android.release.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.x86_64.so"
android.debug.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.x86_32.so"
android.release.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.x86_32.so"
android.debug.arm64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.arm64.so"
android.release.arm64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.arm64.so"
android.debug.arm32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.arm32.so"
android.release.arm32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.arm32.so"

android.debug.double.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.x86_64.so"
android.release.double.x86_64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.x86_64.so"
android.debug.double.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.x86_32.so"
android.release.double.x86_32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.x86_32.so"
android.debug.double.arm64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.arm64.so"
android.release.double.arm64 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.arm64.so"
android.debug.double.arm32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.arm32.so"
android.release.double.arm32 = "res://addons/godot_whisper/bin/libgodot_whisper.android.template_release.double.arm32.so"

web.debug.wasm32 = "res://addons/godot_whisper/bin/libgodot_whisper.web.template_release.wasm32.wasm"
web.release.wasm32 = "res://addons/godot_whisper/bin/libgodot_whisper.web.template_release.wasm32.wasm"
web.debug.double.wasm32 = "res://addons/godot_whisper/bin/libgodot_whisper.web.template_release.double.wasm32.wasm"
web.release.double.wasm32 = "res://addons/godot_whisper/bin/libgodot_whisper.web.template_release.double.wasm32.wasm"

  </code></pre>
</details>

<details>
  <summary>Folder structure</summary>
    <pre><code>
addons/godot_whisper on  master [!?] via C v13.3.0-gcc 
❯ lt
 .
├──  audio_stream_to_text.gd
├──  bin
│   ├──  ggml-metal.metal
│   ├──  libgodot_whisper.android.template_release.arm32.so
│   ├──  libgodot_whisper.android.template_release.arm64.so
│   ├──  libgodot_whisper.android.template_release.double.arm32.so
│   ├──  libgodot_whisper.android.template_release.double.arm64.so
│   ├──  libgodot_whisper.android.template_release.double.x86_32.so
│   ├──  libgodot_whisper.android.template_release.double.x86_64.so
│   ├──  libgodot_whisper.android.template_release.x86_32.so
│   ├──  libgodot_whisper.android.template_release.x86_64.so
│   ├──  libgodot_whisper.ios.template_release.arm64.framework
│   │   ├──  Info.plist
│   │   └──  libgodot_whisper.ios.template_release.arm64
│   ├──  libgodot_whisper.ios.template_release.double.arm64.framework
│   │   ├──  Info.plist
│   │   └──  libgodot_whisper.ios.template_release.double.arm64
│   ├──  libgodot_whisper.linux.template_release.double.x86_64.so
│   ├──  libgodot_whisper.linux.template_release.x86_64.so
│   ├──  libgodot_whisper.macos.template_release.double.universal.framework
│   │   ├──  _CodeSignature
│   │   │   └──  CodeResources
│   │   ├──  libgodot_whisper.macos.template_release.double.universal
│   │   └──  Resources
│   │       └──  Info.plist
│   ├──  libgodot_whisper.macos.template_release.universal.framework
│   │   ├──  _CodeSignature
│   │   │   └──  CodeResources
│   │   ├──  libgodot_whisper.macos.template_release.universal
│   │   └──  Resources
│   │       └──  Info.plist
│   ├──  libgodot_whisper.web.template_release.double.wasm32.wasm
│   ├──  libgodot_whisper.web.template_release.wasm32.wasm
│   ├──  libgodot_whisper.windows.template_release.double.x86_32.dll
│   ├──  libgodot_whisper.windows.template_release.double.x86_64.dll
│   ├──  libgodot_whisper.windows.template_release.x86_32.dll
│   └──  libgodot_whisper.windows.template_release.x86_64.dll
├──  capture_stream_to_text.gd
├──  ggml-metal.metal
├──  godot_whisper.gdextension
├──  label_transcribe.gd
├──  model_downloader.gd
├──  models
│   └──  gglm-tiny.en.bin
├──  plugin.cfg
├──  speech_to_text.cpp
├──  speech_to_text.h
├──  whisper_dock.gd
└──  whisper_dock.tscn
  </code></pre>
</details>

Minimal reproducible repo: https://github.com/snorreks/godot-whisper-bug_SpeechToText_base_class

**Comment by fire** [comment]
Investigating. I will be slow.

**Comment by fire** [comment]
I suspect somehow the shared library isn't being loaded onto your specific linux. "nix" is not a specific Linux distro I am aware of.

**Comment by snorreks** [comment]
The distro is called NixOS, I have a windows laptop as well, i will clone and setup godot there and see if it works there

**Comment by snorreks** [comment]
It is the same problem on Windows 11 Pro

**Comment by fire** [comment]
Can you join our discord? I'm in a middle of a funk, so there are a few folks here who can help.
